//#ifndef QPROPERTYHELPER_H
//#define QPROPERTYHELPER_H
#define SET_QPROP(QPROP_OLDVALUE, QPROP_NEWVALUE,QPROP_SIGNALSEMITTED) if( QPROP_OLDVALUE != QPROP_NEWVALUE ){ QPROP_OLDVALUE = QPROP_NEWVALUE ; QPROP_SIGNALSEMITTED }
//#endif // QPROPERTYHELPER_H
